---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lab-az-ai-http
  namespace: lab-az-ai
spec:
  parentRefs:
    - name: traefik
      sectionName: http
      kind: Gateway

  hostnames:
    - lab-az-ai.private.antoniocaccamo.work

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https


---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lab-az-ai-https
  namespace: lab-az-ai
spec:
  parentRefs:
    - name: traefik
      sectionName: https
      kind: Gateway

  hostnames:
    - lab-az-ai.private.antoniocaccamo.work

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - name: spa-lab-az-ai-service
          port: 80
          