---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dolevf-dvga-ingress-route
  namespace: vulnerables
spec:
  entryPoints:
    - websecure
  tls:
    secretName: tls-secret
  routes:
    - match: Host(`dolevf-dvga-aks.private.antoniocaccamo.work`)
      kind: Rule
      services:
        - name: dolevf-dvga
          port: 80
    # - match: Host(`lab-ms-graph-aks.private.antoniocaccamo.work`) && PathPrefix(`/api`)
    #   kind: Rule
    #   services:
    #     - name: lab-ms-graph
    #       port: 80