apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-lab-az-ai-deploy
  namespace: labs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-az-ai
      component: webapp
  template:
    metadata:
      labels:
        app: lab-az-ai
        component: webapp
    spec:
      imagePullSecrets:
        - name: pcr-secret
      containers:
        - name: webapp-lab-az-ai
          image: registry.private.antoniocaccamo.work/lab-az-ai/webapp-lab-az-ai:1.0.1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
          env:
          - name: TENANT_ID
            valueFrom:
              secretKeyRef:
                name: lab-az-ai
                key: TENANT_ID
          - name: WEBAPP_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: lab-az-ai
                key: WEBAPP_CLIENT_ID
          - name: WEBAPP_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: lab-az-ai
                key: WEBAPP_CLIENT_SECRET