apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-lab-az-ai-deploy
  namespace: labs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-az-ai
      component: spa
  template:
    metadata:
      labels:
        app: lab-az-ai
        component: spa
    spec:
      imagePullSecrets:
        - name: pcr-secret
      containers:
        - name: spa-lab-az-ai
          image: registry.private.antoniocaccamo.work/lab-az-ai/spa-lab-az-ai:1.0.1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
          env:
          - name: TENANT_ID
            valueFrom:
              secretKeyRef:
                name: lab-az-ai
                key: TENANT_ID
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: lab-az-ai
                key: WEBAPP_CLIENT_ID