apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress-route
  namespace: default
spec:
  entryPoints:
    - websecure
  tls:
    secretName: tls-secret

  routes:
  - match: Host(`whoami.private.antoniocaccamo.work`)
    kind: Rule
    middlewares:
      - name: whoami-oidc
    services:
      - name: whoami-service
        port: 80
