# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: lab-az-ai-ingress-route
#   namespace: lab-az-ai
# spec:
#   entryPoints:
#     - websecure
#   tls:
#     secretName: tls-secret

#   routes:
#   - match: Host(`lab-az-ai.private.antoniocaccamo.work`)
#     kind: Rule
#     #middlewares:
#     #  - name: whoami-oidc
#     services:
#       - name: spa-lab-az-ai-service
#         namespace: lab-az-ai
#         port: 80
