apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: whoami-oidc
  namespace: default
spec:
  plugin:
    traefik-oidc-auth:
      Secret: "MlPcD6egVjzEXl7uYiGgoWYxaYUCE6B9"
      Provider:
        Url: "https://login.private.antoniocaccamo.work/realms/labs"
        ClientID: "urn:k8s:secret:keycloak-labs-whoami:clientId"
        ClientSecret: "urn:k8s:secret:keycloak-labs-whoami:clientSecret"
        UsePkce: true
        ValidAudience: "whoami"
