apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-ingress-route
  namespace: cattle-system 
spec:
  entryPoints:
    - websecure
  tls:
    secretName: tls-secret

  routes:
  - match: Host(`rancher.private.antoniocaccamo.work`)
    kind: Rule
#   middlewares:
#      - name: rancher-oidc
    services:
      - name: rancher
        port: 80
